### ISSUE TITLE
无法将panel_day设置为日记模板，调用后仅显示日期

### ISSUE THREAD

**Issue by 5wuuy5** [Crowds21/Organized#1]
无法将panel_day设置为日记模板，调用后仅显示日期
![image](https://user-images.githubusercontent.com/54473739/128304011-7145e673-f30f-47e3-99b4-46668d5a51bb.png)

**Comment by Crowds21** [comment]
> 无法将panel_day设置为日记模板，调用后仅显示日期
> ![image](https://user-images.githubusercontent.com/54473739/128304011-7145e673-f30f-47e3-99b4-46668d5a51bb.png)

试了一下,新建文件自动调用的时候,没有办法获取到文件的ID,这个应该是和思源的文件创建逻辑有关系有关系,等文件全部生成后,再写入数据库.
这个问题我目前想不到解决的办法,哎,难顶.

**Comment by Crowds21** [comment]
你要不就先用旧版的吧. 区别就是一个Recent 和一个昨日编辑的字数
我试着和D大反馈一下这个问题.挺限制模板的功能性的

https://github.com/Crowds21/Organized/blob/1f4d9a58a12405762da72eff15994eba214cc741/templates/dailyTemplate.md

**Comment by 5wuuy5** [comment]
> > 无法将panel_day设置为日记模板，调用后仅显示日期
> > ![image](https://user-images.githubusercontent.com/54473739/128304011-7145e673-f30f-47e3-99b4-46668d5a51bb.png)
> 
> 试了一下,新建文件自动调用的时候,没有办法获取到文件的ID,这个应该是和思源的文件创建逻辑有关系有关系,等文件全部生成后,再写入数据库.
> 这个问题我目前想不到解决的办法,哎,难顶.

嗷嗷，懂了，就是生成这个的时候，它还不在数据库中，所以它没有ID，也没有地址，也就无法利用数据库和其所在位置的信息来统计昨日编辑字数和数据库的Recent？可不可以把这个信息提前写到代码里呢？比如日记的地址一般都是在笔记本中设置好的。

**Comment by 5wuuy5** [comment]
> 你要不就先用旧版的吧. 区别就是一个Recent 和一个昨日编辑的字数
> 我试着和D大反馈一下这个问题.挺限制模板的功能性的
> 
> https://github.com/Crowds21/Organized/blob/1f4d9a58a12405762da72eff15994eba214cc741/templates/dailyTemplate.md

谢谢大佬😁，好使了。但有一个小问题：
![image](https://user-images.githubusercontent.com/54473739/128346340-a735e322-1d7b-408a-b7fb-e53c3246f464.png)
新建以后多一个名字和别名，我看.md文件中也没有写，不知道为什么会多出来。
谢谢大佬耐心迅速地回复~

**Comment by Crowds21** [comment]
> > 你要不就先用旧版的吧. 区别就是一个Recent 和一个昨日编辑的字数
> > 我试着和D大反馈一下这个问题.挺限制模板的功能性的
> > https://github.com/Crowds21/Organized/blob/1f4d9a58a12405762da72eff15994eba214cc741/templates/dailyTemplate.md
> 
> 谢谢大佬😁，好使了。但有一个小问题：
> ![image](https://user-images.githubusercontent.com/54473739/128346340-a735e322-1d7b-408a-b7fb-e53c3246f464.png)
> 新建以后多一个名字和别名，我看.md文件中也没有写，不知道为什么会多出来。
> 谢谢大佬耐心迅速地回复~

这个你比对一下超级块的部分，给{{{后面多设置了一样内联属性，就是 {: name=“” }这里。

至于其他办法的话，等周末再考虑一下吧😂

**Comment by 5wuuy5** [comment]
> > > 你要不就先用旧版的吧. 区别就是一个Recent 和一个昨日编辑的字数
> > > 我试着和D大反馈一下这个问题.挺限制模板的功能性的
> > > https://github.com/Crowds21/Organized/blob/1f4d9a58a12405762da72eff15994eba214cc741/templates/dailyTemplate.md
> > 
> > 
> > 谢谢大佬😁，好使了。但有一个小问题：
> > ![image](https://user-images.githubusercontent.com/54473739/128346340-a735e322-1d7b-408a-b7fb-e53c3246f464.png)
> > 新建以后多一个名字和别名，我看.md文件中也没有写，不知道为什么会多出来。
> > 谢谢大佬耐心迅速地回复~
> 
> 这个你比对一下超级块的部分，给{{{后面多设置了一样内联属性，就是 {: name=“” }这里。
> 
> 至于其他办法的话，等周末再考虑一下吧😂

嗷嗷，看到了，新的里面这里修正了。哈哈哈，当时看到了这句话，没理解也没注意😂。话说这些块的语法在哪里有呢？现在不能用思源笔记直接写模板，好像也没找到哪里有介绍块的语法？这个超级块{{{，还有{{{col看了半天才明白。而且有支持语法的编辑器吗？只能颅内语法高亮和匹配括号😂

**Comment by Crowds21** [comment]
> 嗷嗷，看到了，新的里面这里修正了。哈哈哈，当时看到了这句话，没理解也没注意😂。话说这些块的语法在哪里有呢？现在不能用思源笔记直接写模板，好像也没找到哪里有介绍块的语法？这个超级块{{{，还有{{{col看了半天才明白。而且有支持语法的编辑器吗？只能颅内语法高亮和匹配括号😂

链滴我之前发过一个帖子是 模板基础教程,里面有常见的模板语法. 编辑器现在思源不支持,只能用其他的编辑软件编辑,我一直用的 txt文本编辑器来编辑的. 确实只能靠自我感觉了.
