### ISSUE TITLE
panel_day模板报错

### ISSUE THREAD

**Issue by Jamie-Wan** [Crowds21/Organized#2]
大佬您好！在思源更新到最新版后，发现panel_day模板无法使用，一直报错，其他的没有问题。想请教一下如何解决。感谢大佬！
![download](https://user-images.githubusercontent.com/65280479/162609555-45a3249e-8ae5-433b-ad85-f37a258b9d86.png)

**Comment by Crowds21** [comment]
感谢反馈.
你是自己做过改动吗? 我自己尝试了一下 1.9.9 版本并没有什么问题.
你先试试手动把原本的模板文件覆盖一下呢.

**Comment by Jamie-Wan** [comment]
好的，之前应该是思源自身的bug，升级到最新版后没有这个问题了，感谢大佬！
